### ISSUE TITLE
Target storage selection not saved by the tool

### ISSUE THREAD

**Issue by KamilSzafarczyk** [Azure/migAz#18]
Hi,
I'm exporting an ASM VM with multiple disks to ARM, but the selected target storage isn't remembered by the MigAz v1.5.0.1 tool and resets the selection to the first storage account in the list.

**Comment by rsanderson2350** [comment]
MigAz v2.0.0.0 (which currently includes the next major update) should be released live within the next day, and this should be addressed in that build.  Thanks.

**Comment by rsanderson2350** [comment]
MigAz ASM to ARM v2.0.0.0 is now available - https://github.com/Azure/migAz/tree/master/release

**Comment by KamilSzafarczyk** [comment]
Just tested. V2 has the same issue.

**Comment by rsanderson2350** [comment]
@KamilSzafarczyk I've submitted a Pull Request for MigAz v2.1.0.0, which will likely be merged within the next 12 hours.  Please download and advise if this version resolves the issue.  I was able to observe a problem related to your description, and I believe this is now resolved.  In the event it is not, can you please provide an update on steps to reproduce the issue as well as any error messages?  Thanks!

**Comment by PauloRamosGit** [comment]
Hi @KamilSzafarczyk , can you confirm if v2.2.0.0 still show the issue?

**Comment by KamilSzafarczyk** [comment]
Hi @rsanderson2350 @rsanderson2350 , the issue is fixed in v2.1.0.0. Thanks
